/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  8453: {
    ClawdWorks: {
      address: "0x90c14763fb2a372f186cbb3bfe8a1ed81f90623e",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_clawd",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "BPS_DENOMINATOR",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BURN_ADDRESS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BURN_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "DEFAULT_MAX_ACTIVE_JOBS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "DELIVERY_TIMEOUT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SELLER_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "TREASURY",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "TREASURY_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "activeJobCount",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "cancelJob",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimTimeout",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "clawd",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "confirmReceipt",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createListing",
          inputs: [
            {
              name: "title",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "priceCLAWD",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deliveryDays",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxConcurrentOverride",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "whitelistedBuyer",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deactivateListing",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "expressSellerInterest",
          inputs: [
            {
              name: "pitchIpfsHash",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getJob",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct ClawdWorks.Job",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "listingId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "buyer",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "seller",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amountPaid",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "buyerNoteIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "deliverableIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "deliveredAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum ClawdWorks.JobStatus",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getJobsByBuyer",
          inputs: [
            {
              name: "buyer",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct ClawdWorks.Job[]",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "listingId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "buyer",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "seller",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amountPaid",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "buyerNoteIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "deliverableIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "deliveredAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum ClawdWorks.JobStatus",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getJobsBySeller",
          inputs: [
            {
              name: "seller",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct ClawdWorks.Job[]",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "listingId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "buyer",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "seller",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "amountPaid",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "buyerNoteIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "deliverableIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "deliveredAt",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum ClawdWorks.JobStatus",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getListing",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct ClawdWorks.Listing",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "seller",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "title",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "priceCLAWD",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "deliveryDaysEstimate",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxConcurrentOverride",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "whitelistedBuyer",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getListingsByIds",
          inputs: [
            {
              name: "ids",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          outputs: [
            {
              name: "result",
              type: "tuple[]",
              internalType: "struct ClawdWorks.Listing[]",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "seller",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "title",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "priceCLAWD",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "deliveryDaysEstimate",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxConcurrentOverride",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "whitelistedBuyer",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getReview",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct ClawdWorks.Review",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "jobId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "stars",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "reviewIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "sellerResponseIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "timestamp",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getReviewsByJob",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct ClawdWorks.Review[]",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "jobId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "stars",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "reviewIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "sellerResponseIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "timestamp",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getSellerInterest",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct ClawdWorks.SellerInterest",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "wallet",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "pitchIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "timestamp",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getSellerInterests",
          inputs: [
            {
              name: "from",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "count",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct ClawdWorks.SellerInterest[]",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "wallet",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "pitchIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "timestamp",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getSellerListingIds",
          inputs: [
            {
              name: "seller",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getSellerReview",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct ClawdWorks.SellerReview",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "jobId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "stars",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "reviewIpfsHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "timestamp",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasExpressedInterest",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "jobCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "jobs",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "listingId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "buyer",
              type: "address",
              internalType: "address",
            },
            {
              name: "seller",
              type: "address",
              internalType: "address",
            },
            {
              name: "amountPaid",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "buyerNoteIpfsHash",
              type: "string",
              internalType: "string",
            },
            {
              name: "deliverableIpfsHash",
              type: "string",
              internalType: "string",
            },
            {
              name: "deliveredAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum ClawdWorks.JobStatus",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "listingCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "listings",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "seller",
              type: "address",
              internalType: "address",
            },
            {
              name: "title",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "priceCLAWD",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deliveryDaysEstimate",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxConcurrentOverride",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "whitelistedBuyer",
              type: "address",
              internalType: "address",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "markDelivered",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deliverableIpfsHash",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "maxActiveJobs",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "purchase",
          inputs: [
            {
              name: "listingId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "buyerNoteIpfsHash",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "refundBuyer",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "respondToReview",
          inputs: [
            {
              name: "reviewId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "responseIpfsHash",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "reviewByJob",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "reviewCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "reviews",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "stars",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "reviewIpfsHash",
              type: "string",
              internalType: "string",
            },
            {
              name: "sellerResponseIpfsHash",
              type: "string",
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sellerInterestById",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "pitchIpfsHash",
              type: "string",
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sellerInterestCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sellerListings",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sellerReviewByJob",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sellerReviewCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sellerReviews",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "stars",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "reviewIpfsHash",
              type: "string",
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setMaxActiveJobs",
          inputs: [
            {
              name: "cap",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "submitReview",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "stars",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "reviewIpfsHash",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "submitSellerReview",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "stars",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "reviewIpfsHash",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "updateListing",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "title",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "priceCLAWD",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "deliveryDays",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxConcurrentOverride",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "whitelistedBuyer",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "JobCancelled",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "JobCompleted",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "JobDelivered",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "deliverableIpfsHash",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "JobPurchased",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "listingId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "buyer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "seller",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "amountPaid",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "JobRefunded",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "JobTimeoutClaimed",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ListingCreated",
          inputs: [
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "seller",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "title",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "priceCLAWD",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ListingDeactivated",
          inputs: [
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ListingUpdated",
          inputs: [
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MaxActiveJobsSet",
          inputs: [
            {
              name: "seller",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "cap",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Payout",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "sellerAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "burnAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "treasuryAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ReviewResponded",
          inputs: [
            {
              name: "reviewId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ReviewSubmitted",
          inputs: [
            {
              name: "reviewId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "stars",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SellerInterestExpressed",
          inputs: [
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "wallet",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SellerReviewSubmitted",
          inputs: [
            {
              name: "sellerReviewId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "stars",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 45751749,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
